#!/bin/bash
echo -ne 'stopping old container...'
docker stop automl-container
echo -ne '\t [done]\n'

echo -ne 'building container...'
docker build -t automl-container-backend . 
echo -ne '\t [done]\n'

echo -ne 'starting...'
docker run -d --rm \
--name automl-container \
-p 7531:7531 \
automl-container-backend

echo -ne '\t [done]\n'
docker logs automl-container -f